### ISSUE TITLE
Decide which django releases that should be supported

### ISSUE THREAD

**Issue by relekang** [relekang/django-nopassword#52]
[Django download page](https://www.djangoproject.com/download/) has a list of supported versions.

**Comment by ataylor32** [comment]
For what it's worth, here's an excerpt from [a post on the official Django blog](https://www.djangoproject.com/weblog/2015/jun/25/roadmap/):

**Q: I’m the maintainer of a reusable application. Which Django versions should I support?**

A: We recommend that you support the same Django versions that are supported by the Django team. With the new deprecation policy, it should be possible to support two consecutive LTS releases (e.g. 1.8 and 1.11) and all the non-LTS versions in between without requiring backwards-compatibility shims in your own code, as long as your code runs warning-clean on the lower LTS (1.8), because any non-deprecated feature in one LTS release is guaranteed to remain in place through the next LTS release.
